sudo: required

language: php

services:
  - docker

php:
  - 7.2
  - 7.3
  - 7.4snapshot
  - nightly

matrix:
  allow_failures:
    - php: 7.4snapshot
    - php: nightly
  fast_finish: true

env:
  - AMP_DEBUG=true

before_install:
  - phpenv config-rm xdebug.ini || echo "No xdebug config."
  - docker pull crossbario/autobahn-testsuite
  - docker run -d -v ${PWD}/test-autobahn/config:/config -v ${PWD}/test-autobahn/reports:/reports -p 9001:9001 --name fuzzingserver crossbario/autobahn-testsuite

install:
  - composer update -n --prefer-dist

  - mkdir -p coverage/cov coverage/bin
  - wget https://phar.phpunit.de/phpcov.phar -O coverage/bin/phpcov
  - chmod +x coverage/bin/phpcov

  - composer show

script:
  - phpdbg -qrr vendor/bin/phpunit --verbose --coverage-php coverage/cov/main.cov
  - php test-autobahn/runner.php
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - curl -OL https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.0/coveralls.phar
  - chmod +x coveralls.phar
  - phpdbg -qrr coverage/bin/phpcov merge --clover build/logs/clover.xml coverage/cov
  - ./coveralls.phar

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
