os: linux

language: php

services:
  - docker

php:
  - 7.2
  - 7.3
  - 7.4
  - nightly

jobs:
  allow_failures:
    - php: nightly
  fast_finish: true

env:
  - AMP_DEBUG=true

before_install:
  - docker pull crossbario/autobahn-testsuite
  - docker run -d -v ${PWD}/test-autobahn/config:/config -v ${PWD}/test-autobahn/reports:/reports -p 9001:9001 --name fuzzingserver crossbario/autobahn-testsuite

install:
  - travis_retry composer update -n --prefer-dist

  - mkdir -p coverage/cov coverage/bin
  - wget https://phar.phpunit.de/phpcov.phar -O coverage/bin/phpcov
  - chmod +x coverage/bin/phpcov

script:
  - vendor/bin/phpunit --verbose --coverage-php coverage/cov/main.cov
  - php test-autobahn/runner.php
  - PHP_CS_FIXER_IGNORE_ENV=1 php vendor/bin/php-cs-fixer --diff --dry-run -v fix

after_script:
  - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.2.0/php-coveralls.phar
  - chmod +x php-coveralls.phar
  - coverage/bin/phpcov merge --clover build/logs/clover.xml coverage/cov
  - travis_retry ./php-coveralls.phar -v

cache:
  directories:
    - $HOME/.composer/cache
    - $HOME/.php-cs-fixer
